w <- read.csv("switch_to_prop.csv")
names(w) <- c('x', 'y')
attach(w)
reg <- lm(y~x+I(x^2), w)
summary(reg)
xx <- seq(min(x), max(x), len=200)
yy <- reg$coef %*% rbind(1,xx,xx^2)
plot(y~x, w)
lines(xx,yy,lwd=2,col=2)