function pOpt = find_social_opt(follows, langs, logt, constants, global_k, p0)
%% Find social opt (quite fast)
[n,m] = size(follows);
if nargin >= 6
    pOpt = p0(1:n);
else
    pOpt = rand(n,1);
end

options = optimset('GradObj','on','Display','iter',...
                ...'DerivativeCheck','on',...
                'Hessian','lbfgs',...
                'Algorithm','interior-point'...
                ...'Algorithm','active-set'...
                );
[pOpt,fval,exitflag,output] = fmincon( ...
    @(p)SocialWelfareObjGrad(p, follows, langs, logt, constants, global_k), ...
    pOpt, ...
    [],[],[],[], ...
    zeros(n,1),ones(n,1), ...
    [], options);
end